FROM python:3.9-slim

WORKDIR /app

RUN mkdir -p /app/.wdm && chmod -R 777 /app/.wdm

RUN pip install --upgrade pip \
    && pip install selenium webdriver-manager

COPY . .

CMD ["python3", "test_selenium.py"]
