services:
  web:
    image: ananthvands/book-haven:latest
    ports:
      - "8080:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
